name: Actions sync
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/actions-sync.yml"
      - ".github/actions-sync/**"
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: adrianjost/files-sync-action@v1.0.1
        with:
          COMMIT_MESSAGE: Update GitHub Actions
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_USERNAME: micronaut-build
          GIT_EMAIL: "micronaut-build@users.noreply.github.com"
          FILE_PATTERNS: |-
            ^\.github\/actions-sync\/.*
          TARGET_REPOS: |-
            micronaut-projects/micronaut-rabbitmq

