name: Actions sync
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/**"
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: adrianjost/files-sync-action@v1.0.1
        with:
          COMMIT_MESSAGE: "Update GitHub Actions"
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_USERNAME: micronaut-build
          GIT_EMAIL: "micronaut-build@users.noreply.github.com"
          FILE_PATTERNS: |-
            ^\.github\/actions-sync\/central-sync\.yml$
            ^\.github\/workflows\/dependency-check\.yml$
            ^\.github\/workflows\/gradle\.yml$
            ^\.github\/workflows\/label-sync\.yml$
          TARGET_REPOS: |-
            micronaut-projects/micronaut-rabbitmq

